### ISSUE TITLE
Scheduling at irregular intervals

### ISSUE THREAD

**Issue by arksnorman** [ConnectForLife/openmrs-module-messages#1]
I need help scheduling messages at irregular intervals let's say like send out a call after 2 days, then 2 weeks, and 6 weeks instead of daily or weekly. Have looked at message_templates and I have not been able to find out the best way to do this.

Am kindly asking for some guidance on how to do this.
Thanks

**Comment by pwargulak** [comment]
Hi @arksnorman 
have you been able to find solution? 

It sounds like Visit Reminder, but instead configuring how many days before an event the system sends message, you configure how many after the event. 
The Visit Reminder message service queries can be found here: https://github.com/ConnectForLife/openmrs-cfldistribution-module/tree/main/api/src/main/resources/mysql/services/VisitReminder

**Comment by pgesek** [comment]
We have moved this repository to: https://github.com/johnsonandjohnson/openmrs-module-messages

If the issue still persists, please create it again in that repository. Sorry for the inconvenience.

Regards,
Paweł
